/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	serviceextension_v1alpha1 "k8s.io/ingress-gce/pkg/apis/serviceextension/v1alpha1"
	versioned "k8s.io/ingress-gce/pkg/serviceextension/client/clientset/versioned"
	internalinterfaces "k8s.io/ingress-gce/pkg/serviceextension/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s.io/ingress-gce/pkg/serviceextension/client/listers/serviceextension/v1alpha1"
)

// ServiceExtensionInformer provides access to a shared informer and lister for
// ServiceExtensions.
type ServiceExtensionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ServiceExtensionLister
}

type serviceExtensionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewServiceExtensionInformer constructs a new informer for ServiceExtension type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewServiceExtensionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredServiceExtensionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredServiceExtensionInformer constructs a new informer for ServiceExtension type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredServiceExtensionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1alpha1().ServiceExtensions(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1alpha1().ServiceExtensions(namespace).Watch(options)
			},
		},
		&serviceextension_v1alpha1.ServiceExtension{},
		resyncPeriod,
		indexers,
	)
}

func (f *serviceExtensionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredServiceExtensionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *serviceExtensionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&serviceextension_v1alpha1.ServiceExtension{}, f.defaultInformer)
}

func (f *serviceExtensionInformer) Lister() v1alpha1.ServiceExtensionLister {
	return v1alpha1.NewServiceExtensionLister(f.Informer().GetIndexer())
}
