version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
  labels:
  - docker
  - ok-to-test
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  groups:
    gomod-dependencies:
      patterns:
      - '*'
  labels:
  - go
  - dependencies
  - ok-to-test
- package-ecosystem: gomod
  directory: /hack/tools
  schedule:
    interval: weekly
  groups:
    gomod-dependencies:
      patterns:
      - '*'
  labels:
  - go
  - dependencies
  - ok-to-test
