# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 3600s
options:
  substitution_option: ALLOW_LOOSE
  machineType: E2_HIGHCPU_8
steps:
- name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20230206-8160eea68e
  id: push-images
  entrypoint: bash
  env:
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - REGISTRY=gcr.io/k8s-ingress-image-push
  - VERSION=$_PULL_BASE_REF
  - VERBOSE=1
  - HOME=/root
  - USER=root
  args:
  - -c
  - |
    # Build and push every image except e2e-test 
    make all-push ALL_ARCH="amd64 arm64" \
      CONTAINER_BINARIES="glbc 404-server 404-server-with-metrics echo fuzzer"
- name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20230206-8160eea68e
  id: push-e2e-test-image
  entrypoint: bash
  env:
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - REGISTRY=gcr.io/k8s-ingress-image-push
  - VERSION=$_PULL_BASE_REF
  - VERBOSE=1
  - HOME=/root
  - USER=root
  - BINARIES=e2e-test
  - ADDITIONAL_TAGS=infrastructure-public-image-$_GIT_TAG
  args:
  - -c
  - |
    # Build and push e2e-test image 
    # This image is built separately because it has
    # additional dependencies (curl, gcloud-cli), and
    # requires `docker buildx` for multiarch building process
    gcloud auth configure-docker  \
    && ./hack/push-multiarch.sh
substitutions:
  _GIT_TAG: "12345"
  _PULL_BASE_REF: "main"
