# Copyright 2018 The Kubernetes Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Check End of Life Date wiki.debian.org/DebianReleases
# and replace with a new one if needed
FROM debian:11

#ARG_ARCH & ARG_BIN are replaces with sed in build/rules.mk
ADD bin/ARG_ARCH/ARG_BIN /ARG_BIN

ARG CLOUD_SDK_VERSION="416.0.0"
ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION
ENV PATH /google-cloud-sdk/bin:$PATH

COPY cmd/e2e-test/run.sh /run.sh

# Get architecture for gcloud cli installation
RUN if [ "ARG_ARCH" = "amd64" ]; \
  then echo -n "x86_64" > /tmp/arch; \
  else echo -n "arm" > /tmp/arch; fi;

# Download Google Cloud GPG and install google-cloud-cli
# See recommended instructions:
# cloud.google.com/sdk/docs/install#installation_instructions
RUN ARCH=`cat /tmp/arch` && \
  apt-get update && \
  apt-get install -y curl python apt-transport-https ca-certificates gnupg && \
  curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${CLOUD_SDK_VERSION}-linux-${ARCH}.tar.gz && \
  tar xvf google-cloud-cli-${CLOUD_SDK_VERSION}-linux-${ARCH}.tar.gz && \
  rm google-cloud-cli-${CLOUD_SDK_VERSION}-linux-${ARCH}.tar.gz 

ENTRYPOINT ["/run.sh"]
