# Copyright 2018 The Kubernetes Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Check End of Life Date wiki.debian.org/DebianReleases
# and replace with a new one if needed
# debian_component_based google-cloud-cli image supports arm64/amd64 architectures
# and has curl, gcloud, and ca-certificated preinstalled
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based

#ARG_ARCH & ARG_BIN are replaces with sed in build/rules.mk
ADD bin/ARG_ARCH/ARG_BIN /ARG_BIN
COPY cmd/e2e-test/run.sh /run.sh

ENTRYPOINT ["/run.sh"]
