apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-controller
spec:
  selector:
    matchLabels:
      app: workload-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: workload-controller
    spec:
      serviceAccountName: workload-controller
      containers:
      - name: workload-controller
        image: gcr.io/mixia-cube/workload-controller:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 80
