apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workload
rules:
  - apiGroups: ["networking.gke.io"]
    resources: ["workloads"]
    verbs: ["get", "list", "create", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workload-controller
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update", "create", "patch"]
  - apiGroups: ["networking.gke.io"]
    resources: ["workloads"]
    verbs: ["get", "list", "create", "watch", "update", "patch", "delete", "deletecollection"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "create", "watch", "update", "patch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workload
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload
subjects:
  - kind: ServiceAccount
    name: workload
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workload-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload-controller
subjects:
  - kind: ServiceAccount
    name: workload-controller
    namespace: default
