/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1"
)

// FakeNetworkEndpointGroupBindings implements NetworkEndpointGroupBindingInterface
type FakeNetworkEndpointGroupBindings struct {
	Fake *FakeNetworkingV1beta1
	ns   string
}

var networkendpointgroupbindingsResource = schema.GroupVersionResource{Group: "networking.gke.io", Version: "v1beta1", Resource: "networkendpointgroupbindings"}

var networkendpointgroupbindingsKind = schema.GroupVersionKind{Group: "networking.gke.io", Version: "v1beta1", Kind: "NetworkEndpointGroupBinding"}

// Get takes name of the networkEndpointGroupBinding, and returns the corresponding networkEndpointGroupBinding object, and an error if there is any.
func (c *FakeNetworkEndpointGroupBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NetworkEndpointGroupBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networkendpointgroupbindingsResource, c.ns, name), &v1beta1.NetworkEndpointGroupBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetworkEndpointGroupBinding), err
}

// List takes label and field selectors, and returns the list of NetworkEndpointGroupBindings that match those selectors.
func (c *FakeNetworkEndpointGroupBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NetworkEndpointGroupBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networkendpointgroupbindingsResource, networkendpointgroupbindingsKind, c.ns, opts), &v1beta1.NetworkEndpointGroupBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.NetworkEndpointGroupBindingList{ListMeta: obj.(*v1beta1.NetworkEndpointGroupBindingList).ListMeta}
	for _, item := range obj.(*v1beta1.NetworkEndpointGroupBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkEndpointGroupBindings.
func (c *FakeNetworkEndpointGroupBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networkendpointgroupbindingsResource, c.ns, opts))

}

// Create takes the representation of a networkEndpointGroupBinding and creates it.  Returns the server's representation of the networkEndpointGroupBinding, and an error, if there is any.
func (c *FakeNetworkEndpointGroupBindings) Create(ctx context.Context, networkEndpointGroupBinding *v1beta1.NetworkEndpointGroupBinding, opts v1.CreateOptions) (result *v1beta1.NetworkEndpointGroupBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networkendpointgroupbindingsResource, c.ns, networkEndpointGroupBinding), &v1beta1.NetworkEndpointGroupBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetworkEndpointGroupBinding), err
}

// Update takes the representation of a networkEndpointGroupBinding and updates it. Returns the server's representation of the networkEndpointGroupBinding, and an error, if there is any.
func (c *FakeNetworkEndpointGroupBindings) Update(ctx context.Context, networkEndpointGroupBinding *v1beta1.NetworkEndpointGroupBinding, opts v1.UpdateOptions) (result *v1beta1.NetworkEndpointGroupBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networkendpointgroupbindingsResource, c.ns, networkEndpointGroupBinding), &v1beta1.NetworkEndpointGroupBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetworkEndpointGroupBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkEndpointGroupBindings) UpdateStatus(ctx context.Context, networkEndpointGroupBinding *v1beta1.NetworkEndpointGroupBinding, opts v1.UpdateOptions) (*v1beta1.NetworkEndpointGroupBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(networkendpointgroupbindingsResource, "status", c.ns, networkEndpointGroupBinding), &v1beta1.NetworkEndpointGroupBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetworkEndpointGroupBinding), err
}

// Delete takes name of the networkEndpointGroupBinding and deletes it. Returns an error if one occurs.
func (c *FakeNetworkEndpointGroupBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(networkendpointgroupbindingsResource, c.ns, name), &v1beta1.NetworkEndpointGroupBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkEndpointGroupBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networkendpointgroupbindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.NetworkEndpointGroupBindingList{})
	return err
}

// Patch applies the patch and returns the patched networkEndpointGroupBinding.
func (c *FakeNetworkEndpointGroupBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetworkEndpointGroupBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkendpointgroupbindingsResource, c.ns, name, pt, data, subresources...), &v1beta1.NetworkEndpointGroupBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetworkEndpointGroupBinding), err
}
