/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	providerconfigv1 "k8s.io/ingress-gce/pkg/apis/providerconfig/v1"
	versioned "k8s.io/ingress-gce/pkg/providerconfig/client/clientset/versioned"
	internalinterfaces "k8s.io/ingress-gce/pkg/providerconfig/client/informers/externalversions/internalinterfaces"
	v1 "k8s.io/ingress-gce/pkg/providerconfig/client/listers/providerconfig/v1"
)

// ProviderConfigInformer provides access to a shared informer and lister for
// ProviderConfigs.
type ProviderConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ProviderConfigLister
}

type providerConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewProviderConfigInformer constructs a new informer for ProviderConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewProviderConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredProviderConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredProviderConfigInformer constructs a new informer for ProviderConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredProviderConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1().ProviderConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1().ProviderConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&providerconfigv1.ProviderConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *providerConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredProviderConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *providerConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&providerconfigv1.ProviderConfig{}, f.defaultInformer)
}

func (f *providerConfigInformer) Lister() v1.ProviderConfigLister {
	return v1.NewProviderConfigLister(f.Informer().GetIndexer())
}
