// +build !ignore_autogenerated

/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerForwardingRule) DeepCopyInto(out *ConsumerForwardingRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerForwardingRule.
func (in *ConsumerForwardingRule) DeepCopy() *ConsumerForwardingRule {
	if in == nil {
		return nil
	}
	out := new(ConsumerForwardingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerProject) DeepCopyInto(out *ConsumerProject) {
	*out = *in
	if in.ForceSendFields != nil {
		in, out := &in.ForceSendFields, &out.ForceSendFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NullFields != nil {
		in, out := &in.NullFields, &out.NullFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerProject.
func (in *ConsumerProject) DeepCopy() *ConsumerProject {
	if in == nil {
		return nil
	}
	out := new(ConsumerProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachment) DeepCopyInto(out *ServiceAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachment.
func (in *ServiceAttachment) DeepCopy() *ServiceAttachment {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentList) DeepCopyInto(out *ServiceAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentList.
func (in *ServiceAttachmentList) DeepCopy() *ServiceAttachmentList {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentSpec) DeepCopyInto(out *ServiceAttachmentSpec) {
	*out = *in
	if in.NATSubnets != nil {
		in, out := &in.NATSubnets, &out.NATSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ResourceRef.DeepCopyInto(&out.ResourceRef)
	if in.ConsumerAllowList != nil {
		in, out := &in.ConsumerAllowList, &out.ConsumerAllowList
		*out = make([]ConsumerProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConsumerRejectList != nil {
		in, out := &in.ConsumerRejectList, &out.ConsumerRejectList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentSpec.
func (in *ServiceAttachmentSpec) DeepCopy() *ServiceAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAttachmentStatus) DeepCopyInto(out *ServiceAttachmentStatus) {
	*out = *in
	if in.ConsumerForwardingRules != nil {
		in, out := &in.ConsumerForwardingRules, &out.ConsumerForwardingRules
		*out = make([]ConsumerForwardingRule, len(*in))
		copy(*out, *in)
	}
	in.LastModifiedTimestamp.DeepCopyInto(&out.LastModifiedTimestamp)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAttachmentStatus.
func (in *ServiceAttachmentStatus) DeepCopy() *ServiceAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}
