/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1 "k8s.io/ingress-gce/pkg/apis/serviceattachment/v1"
	scheme "k8s.io/ingress-gce/pkg/serviceattachment/client/clientset/versioned/scheme"
)

// ServiceAttachmentsGetter has a method to return a ServiceAttachmentInterface.
// A group's client should implement this interface.
type ServiceAttachmentsGetter interface {
	ServiceAttachments(namespace string) ServiceAttachmentInterface
}

// ServiceAttachmentInterface has methods to work with ServiceAttachment resources.
type ServiceAttachmentInterface interface {
	Create(ctx context.Context, serviceAttachment *v1.ServiceAttachment, opts metav1.CreateOptions) (*v1.ServiceAttachment, error)
	Update(ctx context.Context, serviceAttachment *v1.ServiceAttachment, opts metav1.UpdateOptions) (*v1.ServiceAttachment, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, serviceAttachment *v1.ServiceAttachment, opts metav1.UpdateOptions) (*v1.ServiceAttachment, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ServiceAttachment, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ServiceAttachmentList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ServiceAttachment, err error)
	ServiceAttachmentExpansion
}

// serviceAttachments implements ServiceAttachmentInterface
type serviceAttachments struct {
	*gentype.ClientWithList[*v1.ServiceAttachment, *v1.ServiceAttachmentList]
}

// newServiceAttachments returns a ServiceAttachments
func newServiceAttachments(c *NetworkingV1Client, namespace string) *serviceAttachments {
	return &serviceAttachments{
		gentype.NewClientWithList[*v1.ServiceAttachment, *v1.ServiceAttachmentList](
			"serviceattachments",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.ServiceAttachment { return &v1.ServiceAttachment{} },
			func() *v1.ServiceAttachmentList { return &v1.ServiceAttachmentList{} }),
	}
}
