/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/ingress-gce/pkg/apis/serviceextension/v1alpha1"
)

// FakeServiceExtensions implements ServiceExtensionInterface
type FakeServiceExtensions struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var serviceextensionsResource = schema.GroupVersionResource{Group: "cloud.google.com", Version: "v1alpha1", Resource: "serviceextensions"}

var serviceextensionsKind = schema.GroupVersionKind{Group: "cloud.google.com", Version: "v1alpha1", Kind: "ServiceExtension"}

// Get takes name of the serviceExtension, and returns the corresponding serviceExtension object, and an error if there is any.
func (c *FakeServiceExtensions) Get(name string, options v1.GetOptions) (result *v1alpha1.ServiceExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(serviceextensionsResource, c.ns, name), &v1alpha1.ServiceExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceExtension), err
}

// List takes label and field selectors, and returns the list of ServiceExtensions that match those selectors.
func (c *FakeServiceExtensions) List(opts v1.ListOptions) (result *v1alpha1.ServiceExtensionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(serviceextensionsResource, serviceextensionsKind, c.ns, opts), &v1alpha1.ServiceExtensionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServiceExtensionList{}
	for _, item := range obj.(*v1alpha1.ServiceExtensionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceExtensions.
func (c *FakeServiceExtensions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(serviceextensionsResource, c.ns, opts))

}

// Create takes the representation of a serviceExtension and creates it.  Returns the server's representation of the serviceExtension, and an error, if there is any.
func (c *FakeServiceExtensions) Create(serviceExtension *v1alpha1.ServiceExtension) (result *v1alpha1.ServiceExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(serviceextensionsResource, c.ns, serviceExtension), &v1alpha1.ServiceExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceExtension), err
}

// Update takes the representation of a serviceExtension and updates it. Returns the server's representation of the serviceExtension, and an error, if there is any.
func (c *FakeServiceExtensions) Update(serviceExtension *v1alpha1.ServiceExtension) (result *v1alpha1.ServiceExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(serviceextensionsResource, c.ns, serviceExtension), &v1alpha1.ServiceExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceExtension), err
}

// Delete takes name of the serviceExtension and deletes it. Returns an error if one occurs.
func (c *FakeServiceExtensions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(serviceextensionsResource, c.ns, name), &v1alpha1.ServiceExtension{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceExtensions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(serviceextensionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServiceExtensionList{})
	return err
}

// Patch applies the patch and returns the patched serviceExtension.
func (c *FakeServiceExtensions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServiceExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(serviceextensionsResource, c.ns, name, data, subresources...), &v1alpha1.ServiceExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceExtension), err
}
