/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1 "k8s.io/ingress-gce/pkg/apis/l4lbconfig/v1"
)

// L4LBConfigLister helps list L4LBConfigs.
// All objects returned here must be treated as read-only.
type L4LBConfigLister interface {
	// List lists all L4LBConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.L4LBConfig, err error)
	// L4LBConfigs returns an object that can list and get L4LBConfigs.
	L4LBConfigs(namespace string) L4LBConfigNamespaceLister
	L4LBConfigListerExpansion
}

// l4LBConfigLister implements the L4LBConfigLister interface.
type l4LBConfigLister struct {
	indexer cache.Indexer
}

// NewL4LBConfigLister returns a new L4LBConfigLister.
func NewL4LBConfigLister(indexer cache.Indexer) L4LBConfigLister {
	return &l4LBConfigLister{indexer: indexer}
}

// List lists all L4LBConfigs in the indexer.
func (s *l4LBConfigLister) List(selector labels.Selector) (ret []*v1.L4LBConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.L4LBConfig))
	})
	return ret, err
}

// L4LBConfigs returns an object that can list and get L4LBConfigs.
func (s *l4LBConfigLister) L4LBConfigs(namespace string) L4LBConfigNamespaceLister {
	return l4LBConfigNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// L4LBConfigNamespaceLister helps list and get L4LBConfigs.
// All objects returned here must be treated as read-only.
type L4LBConfigNamespaceLister interface {
	// List lists all L4LBConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.L4LBConfig, err error)
	// Get retrieves the L4LBConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.L4LBConfig, error)
	L4LBConfigNamespaceListerExpansion
}

// l4LBConfigNamespaceLister implements the L4LBConfigNamespaceLister
// interface.
type l4LBConfigNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all L4LBConfigs in the indexer for a given namespace.
func (s l4LBConfigNamespaceLister) List(selector labels.Selector) (ret []*v1.L4LBConfig, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.L4LBConfig))
	})
	return ret, err
}

// Get retrieves the L4LBConfig from the indexer for a given namespace and name.
func (s l4LBConfigNamespaceLister) Get(name string) (*v1.L4LBConfig, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("l4lbconfig"), name)
	}
	return obj.(*v1.L4LBConfig), nil
}
