/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	svcnegv1beta1 "k8s.io/ingress-gce/pkg/apis/svcneg/v1beta1"
	versioned "k8s.io/ingress-gce/pkg/svcneg/client/clientset/versioned"
	internalinterfaces "k8s.io/ingress-gce/pkg/svcneg/client/informers/externalversions/internalinterfaces"
	v1beta1 "k8s.io/ingress-gce/pkg/svcneg/client/listers/svcneg/v1beta1"
)

// ServiceNetworkEndpointGroupInformer provides access to a shared informer and lister for
// ServiceNetworkEndpointGroups.
type ServiceNetworkEndpointGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ServiceNetworkEndpointGroupLister
}

type serviceNetworkEndpointGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewServiceNetworkEndpointGroupInformer constructs a new informer for ServiceNetworkEndpointGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewServiceNetworkEndpointGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredServiceNetworkEndpointGroupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredServiceNetworkEndpointGroupInformer constructs a new informer for ServiceNetworkEndpointGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredServiceNetworkEndpointGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1beta1().ServiceNetworkEndpointGroups(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1beta1().ServiceNetworkEndpointGroups(namespace).Watch(context.TODO(), options)
			},
		},
		&svcnegv1beta1.ServiceNetworkEndpointGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *serviceNetworkEndpointGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredServiceNetworkEndpointGroupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *serviceNetworkEndpointGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&svcnegv1beta1.ServiceNetworkEndpointGroup{}, f.defaultInformer)
}

func (f *serviceNetworkEndpointGroupInformer) Lister() v1beta1.ServiceNetworkEndpointGroupLister {
	return v1beta1.NewServiceNetworkEndpointGroupLister(f.Informer().GetIndexer())
}
